version: '3.8'

services:
  postgresql:
    image: postgres:alpine
    container_name: postgres-soup
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres-soup
      - POSTGRES_PASSWORD=postgres-soup
      - POSTGRES_DATABASE=postgres-soup
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-soup
    ports:
      - '6379-6379'
